doc:  minutes for deep dives at Jun Collab summit
nodejs/next-10 pull request #134
Opened 2022-06-14 19:51 UTC by mhdawson

Signed-off-by: Michael Dawson <mdawson@devrus.com>

2022-06-14 19:54 UTC, mhdawson commented
Still need to get the link for the recording. Looked in Node.js youtube but did not find it.

Reached out to @waleed to see if he knows were it is.

2022-06-23 06:26 UTC, sheplu requested changes
Just a few typo / changes then I think it will be good to be merged

2022-06-23 06:26 UTC, sheplu commented on meetings/summit-jun-2022.md
> +  * Matteo, one use case that was good for ESM, lamda with top level await, with reserved capacity, can move pre-loading
```suggestion
  * Matteo, one use case that was good for ESM, lambda with top level await, with reserved capacity, can move pre-loading
```

2022-06-23 06:26 UTC, sheplu commented on meetings/summit-jun-2022.md
> +    * Node clinic, need to load before before event loop starts, if start later then miss some objects
```suggestion
    * Node clinic, need to load before event loop starts, if start later then miss some objects
```

2022-06-23 15:59 UTC, trivikr commented on meetings/summit-jun-2022.md
> +  * Better advocacy to module owners, primining them for PRs from APMs etc and communicating best pratices
priming?
```suggestion
  * Better advocacy to module owners, priming them for PRs from APMs etc and communicating best pratices
```

2022-06-23 15:59 UTC, trivikr commented on meetings/summit-jun-2022.md
> +  * Initiate work on enhanded startup lifecycle than can be used to ensure Observability tools are loaded
```suggestion
  * Initiate work on enhanced startup lifecycle than can be used to ensure Observability tools are loaded
```

2022-06-27 22:36 UTC, sheplu approved these changes

2022-06-27 23:40 UTC, trivikr approved these changes

2022-06-28 19:18 UTC, merged